In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5,6]
arr = np.array(list)

In [5]:
arr[2:] = 500

In [10]:
arr / 2

array([  0.5,   1. , 250. , 250. , 250. , 250. ])

In [25]:
arr < 500

array([ True,  True, False, False, False, False])

In [16]:
arr[arr < 4]

array([1, 2])

In [26]:
arr

array([  1,   2, 500, 500, 500, 500])

In [28]:
arr[arr < 1000]

array([  1,   2, 500, 500, 500, 500])

In [67]:
random_uniform = np.random.rand(3,2)
random_uniform

array([[0.01081624, 0.27431505],
       [0.53575911, 0.19285653],
       [0.3064802 , 0.2524072 ]])

In [127]:
random_normal = np.random.randn(3,2)
random_normal

array([[ 0.09521388,  0.07110507],
       [-0.56140885, -2.9330806 ],
       [ 1.18834949,  1.94740422]])

In [244]:
random_ints = np.random.randint(0,10,(1,2))
random_ints

array([[7, 0]])

In [265]:
random_choice = np.random.choice(arr, 3)
random_choice

array([500, 500, 500])

In [274]:
ar = np.full((3,3), 7)
ar

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [279]:
condition = np.where(arr > 2, arr, 'Aayu')
condition

array(['Aayu', 'Aayu', '500', '500', '500', '500'], dtype='<U11')

In [293]:
taken = np.take(arr, [1,2])
taken

array([  2, 500])